//first_name: faker.name.firstName(),
//last_name: faker.name.lastName(),
//gender: faker.name.gender(),
//activity: faker.company.catchPhrase(),
//nrc: faker.name.jobArea(),
//nif: faker.commerce.color(),